db:
  path: dictionary
  driver: QSQLITE
  scripts:
    createDictationEntry: scripts\sql\createDictationEntryTable.sql
    createDictation: scripts\sql\createDictationTable.sql
    createDictionaryEntry: scripts\sql\createDictionaryEntryTable.sql
    createDictionaryEntryTag: scripts\sql\createDictionaryEntryTagTable.sql
    createTag: scripts\sql\createTagTable.sql
    createTranslation: scripts\sql\createTranslationTable.sql
    createVocabulary: scripts\sql\createVocabularyTable.sql
    createWord: scripts\sql\createWordTable.sql
    insertVocabulary: scripts\sql\insertDictionary.sql
    insertWord: scripts\sql\insertWord.sql
    insertTranslation: scripts\sql\insertTranslation.sql
    insertTag: scripts\sql\insertTag.sql
    insertDictation: scripts\sql\insertDictation.sql
    insertDictationEntry: scripts\sql\insertDictationEntry.sql
    insertDictionaryEntry: scripts\sql\insertDictionaryEntry.sql
    insertDictionaryEntryTag: scripts\sql\insertDictionaryEntryTag.sql
    readDictionaries: scripts\sql\readDictionaries.sql
    readDictionaryWords: scripts\sql\readDictionaryWords.sql
    readVocabId: scripts\sql\readVocabId.sql
    readWordId: scripts\sql\readWordId.sql
    readTranslationId: scripts\sql\readTranslationId.sql
    deleteDictionary: scripts\sql\deleteDictionary.sql
    deleteDictionaryEntries: scripts\sql\deleteDictionaryEntries.sql
    deleteDictionaryEntry: scripts\sql\deleteDictionaryEntry.sql
ui:
  title: Glossia
